# Generated by Django 5.2.4 on 2025-07-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre Franquicia')),
            ],
            options={
                'verbose_name': 'Franquicia',
                'verbose_name_plural': 'Franquicias',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_s', models.CharField(max_length=100, verbose_name='Nombre Sucursal')),
                ('Franquicia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.franquicia', verbose_name='Franquicia')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_p', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
