# Generated by Django 5.2.4 on 2025-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
